//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_SAP.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restaurant_SAP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Button_AceptarPedido {
            get {
                return ResourceManager.GetString("Button_AceptarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Mesa.
        /// </summary>
        public static string Button_AgregarNuevaMesa {
            get {
                return ResourceManager.GetString("Button_AgregarNuevaMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Menu.
        /// </summary>
        public static string Button_AgregarNuevoMenu {
            get {
                return ResourceManager.GetString("Button_AgregarNuevoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Pedido.
        /// </summary>
        public static string Button_AgregarPedidoMesa {
            get {
                return ResourceManager.GetString("Button_AgregarPedidoMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Button_AgregarReserva {
            get {
                return ResourceManager.GetString("Button_AgregarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Button_BuscarPedidos {
            get {
                return ResourceManager.GetString("Button_BuscarPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Button_Cancelar {
            get {
                return ResourceManager.GetString("Button_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Button_CancelarMenu {
            get {
                return ResourceManager.GetString("Button_CancelarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Button_CancelarMesa {
            get {
                return ResourceManager.GetString("Button_CancelarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Button_CancelarPedido {
            get {
                return ResourceManager.GetString("Button_CancelarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Button_CancelarReserva {
            get {
                return ResourceManager.GetString("Button_CancelarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string Button_Configuracion {
            get {
                return ResourceManager.GetString("Button_Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Button_EliminarMenu {
            get {
                return ResourceManager.GetString("Button_EliminarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Button_EliminarMesa {
            get {
                return ResourceManager.GetString("Button_EliminarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Button_EliminarReserva {
            get {
                return ResourceManager.GetString("Button_EliminarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar PDF.
        /// </summary>
        public static string Button_GenerarPDF {
            get {
                return ResourceManager.GetString("Button_GenerarPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Button_Guardar {
            get {
                return ResourceManager.GetString("Button_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Button_GuardarMenu {
            get {
                return ResourceManager.GetString("Button_GuardarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Button_GuardarMesa {
            get {
                return ResourceManager.GetString("Button_GuardarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Button_GuardarReserva {
            get {
                return ResourceManager.GetString("Button_GuardarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar Mesa.
        /// </summary>
        public static string Button_PagarMesa {
            get {
                return ResourceManager.GetString("Button_PagarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido Servido.
        /// </summary>
        public static string Button_PedidoServido {
            get {
                return ResourceManager.GetString("Button_PedidoServido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Seleccionar Mesa --.
        /// </summary>
        public static string ComboBox_SeleccionarMesa {
            get {
                return ResourceManager.GetString("ComboBox_SeleccionarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Menú.
        /// </summary>
        public static string GridViewColumn_DescripcionMenu {
            get {
                return ResourceManager.GetString("GridViewColumn_DescripcionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha/Hora.
        /// </summary>
        public static string GridViewColumn_FechaHora {
            get {
                return ResourceManager.GetString("GridViewColumn_FechaHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Menú.
        /// </summary>
        public static string GridViewColumn_NombreMenu {
            get {
                return ResourceManager.GetString("GridViewColumn_NombreMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Mesa.
        /// </summary>
        public static string GridViewColumn_NumeroMesaHistorial {
            get {
                return ResourceManager.GetString("GridViewColumn_NumeroMesaHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string GridViewColumn_PrecioHistorial {
            get {
                return ResourceManager.GetString("GridViewColumn_PrecioHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición de Menu.
        /// </summary>
        public static string GroupBox_EdicionMenu {
            get {
                return ResourceManager.GetString("GroupBox_EdicionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición de Mesa.
        /// </summary>
        public static string GroupBox_EdicionMesa {
            get {
                return ResourceManager.GetString("GroupBox_EdicionMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición de Reserva.
        /// </summary>
        public static string GroupBox_EdicionReserva {
            get {
                return ResourceManager.GetString("GroupBox_EdicionReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Mesa.
        /// </summary>
        public static string GroupBox_NuevaMesa {
            get {
                return ResourceManager.GetString("GroupBox_NuevaMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Menu.
        /// </summary>
        public static string GroupBox_NuevoMenu {
            get {
                return ResourceManager.GetString("GroupBox_NuevoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string ListBox_Menus_Descripcion {
            get {
                return ResourceManager.GetString("ListBox_Menus_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string ListBox_Menus_Nombre {
            get {
                return ResourceManager.GetString("ListBox_Menus_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string ListBox_Menus_Precio {
            get {
                return ResourceManager.GetString("ListBox_Menus_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string ListBox_Mesas_Descripcion {
            get {
                return ResourceManager.GetString("ListBox_Mesas_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string ListBox_Mesas_Estado {
            get {
                return ResourceManager.GetString("ListBox_Mesas_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        public static string ListBox_Mesas_Numero {
            get {
                return ResourceManager.GetString("ListBox_Mesas_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string ListBox_Pedidos_Cantidad {
            get {
                return ResourceManager.GetString("ListBox_Pedidos_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string ListBox_Pedidos_EstadoPedido {
            get {
                return ResourceManager.GetString("ListBox_Pedidos_EstadoPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Menú.
        /// </summary>
        public static string ListBox_Pedidos_MenuDescripcion {
            get {
                return ResourceManager.GetString("ListBox_Pedidos_MenuDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Menú.
        /// </summary>
        public static string ListBox_Pedidos_MenuNombre {
            get {
                return ResourceManager.GetString("ListBox_Pedidos_MenuNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Mesa.
        /// </summary>
        public static string ListBox_Pedidos_MesaNumero {
            get {
                return ResourceManager.GetString("ListBox_Pedidos_MesaNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string ListBox_Pedidos_Precio {
            get {
                return ResourceManager.GetString("ListBox_Pedidos_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin:.
        /// </summary>
        public static string ListBox_Reservas_FechaFin {
            get {
                return ResourceManager.GetString("ListBox_Reservas_FechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio:.
        /// </summary>
        public static string ListBox_Reservas_FechaInicio {
            get {
                return ResourceManager.GetString("ListBox_Reservas_FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar Menú.
        /// </summary>
        public static string TabHeader_AdministrarMenu {
            get {
                return ResourceManager.GetString("TabHeader_AdministrarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar Mesas.
        /// </summary>
        public static string TabHeader_AdministrarMesas {
            get {
                return ResourceManager.GetString("TabHeader_AdministrarMesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar Reservas.
        /// </summary>
        public static string TabHeader_AdministrarReservas {
            get {
                return ResourceManager.GetString("TabHeader_AdministrarReservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial Económico.
        /// </summary>
        public static string TabHeader_HistorialEconomico {
            get {
                return ResourceManager.GetString("TabHeader_HistorialEconomico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapa de Mesas.
        /// </summary>
        public static string TabHeader_MapaMesas {
            get {
                return ResourceManager.GetString("TabHeader_MapaMesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mesas y Pedidos.
        /// </summary>
        public static string TabHeader_MesasPedidos {
            get {
                return ResourceManager.GetString("TabHeader_MesasPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregando Pedido.
        /// </summary>
        public static string TextBlock_AgregandoPedido {
            get {
                return ResourceManager.GetString("TextBlock_AgregandoPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad:.
        /// </summary>
        public static string TextBlock_Cantidad {
            get {
                return ResourceManager.GetString("TextBlock_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        public static string TextBlock_DescripcionMenu {
            get {
                return ResourceManager.GetString("TextBlock_DescripcionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        public static string TextBlock_DescripcionMesa {
            get {
                return ResourceManager.GetString("TextBlock_DescripcionMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde:.
        /// </summary>
        public static string TextBlock_DesdeFecha {
            get {
                return ResourceManager.GetString("TextBlock_DesdeFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado:.
        /// </summary>
        public static string TextBlock_EstadoMesa {
            get {
                return ResourceManager.GetString("TextBlock_EstadoMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar por Menú:.
        /// </summary>
        public static string TextBlock_FiltrarPorMenu {
            get {
                return ResourceManager.GetString("TextBlock_FiltrarPorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar por Mesa:.
        /// </summary>
        public static string TextBlock_FiltrarPorMesa {
            get {
                return ResourceManager.GetString("TextBlock_FiltrarPorMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta:.
        /// </summary>
        public static string TextBlock_HastaFecha {
            get {
                return ResourceManager.GetString("TextBlock_HastaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Icono Mesa].
        /// </summary>
        public static string TextBlock_IconoMesa {
            get {
                return ResourceManager.GetString("TextBlock_IconoMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú:.
        /// </summary>
        public static string TextBlock_Menu {
            get {
                return ResourceManager.GetString("TextBlock_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mesa Seleccionada: .
        /// </summary>
        public static string TextBlock_MesaSeleccionada {
            get {
                return ResourceManager.GetString("TextBlock_MesaSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        public static string TextBlock_NombreMenu {
            get {
                return ResourceManager.GetString("TextBlock_NombreMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número:.
        /// </summary>
        public static string TextBlock_NumeroMesa {
            get {
                return ResourceManager.GetString("TextBlock_NumeroMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        public static string TextBlock_PrecioMenu {
            get {
                return ResourceManager.GetString("TextBlock_PrecioMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Idioma.
        /// </summary>
        public static string TextBlock_SeleccionarIdioma {
            get {
                return ResourceManager.GetString("TextBlock_SeleccionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total:.
        /// </summary>
        public static string TextBlock_Total {
            get {
                return ResourceManager.GetString("TextBlock_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Restaurante SAP.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
